services:
  app:
    build: .
    container_name: app
    ports:
      - "5000:5000"
    links:
      - db
    networks:
      - mired
    depends_on:
      - db
    volumes:
      - ./app:/app
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
  db:
    image: mysql:8.0
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_CHARSET: utf8mb4
    ports:
      - "3306:3306"
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./app/bd/bd.sql:/docker-entrypoint-initdb.d/bd.sql
      - db_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - mired
  #frontend:
  #  build:
  #    context: ./frontend
  #    dockerfile: Dockerfile
  #  container_name: frontend
  #  ports:
  #    - "3000:80"
  #  networks:
  #    - mired

networks:
  mired:

volumes:
  db_data:
